heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a redis cluster on Rackspace Cloud Servers
  along with a sentinel on each slave to automate promotion of a new master
  when the existing one fails.


parameters:

  server_flavor:
    description: Rackspace Cloud Server flavor
    type: string
    default: 1 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  image:
    label: Server Image
    description: Operating system to use for created servers
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 13.10 (Saucy Salamander)
      description: Must be a supported operating system.

  redis_master_hostname:
    description: Hostname for nominal redis master
    type: string
    default: redis-master

  redis_slave_hostname:
    description: Hostname for the slaves
    type: string
    default: redis-slave

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the servers
    type: string
    default: redis

  slave_node_count:
    description: Number of slave nodes to create
    type: number
    default: 2
    constraints:
      - range: { min: 2 }

  slave_server_hostname:
    description: hostname for slave servers
    type: string
    default: redis-slave

resources:

  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  redis_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  redis_master:
    type: Rackspace::Cloud::Server
    depends_on: ssh_key
    properties:
      name: { get_param: redis_master_hostname }
      flavor: { get_param: server_flavor }
      image: Ubuntu 12.04 LTS (Precise Pangolin)
      key_name: { get_resource: ssh_key }

  redis_master_config:
    type: OS::Heat::ChefSolo
    depends_on: redis_master
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [redis_master, accessIPv4] }
      Berksfile: |
        site :opscode
        cookbook 'apt'
        cookbook 'build-essential', '= 1.4.2'
        cookbook 'redisio',
          :git => 'https://github.com/JasonBoyles/redisio.git',
          :branch => '2.0.0_wip'
      node:
        run_list: [ "recipe[apt]",
                    "recipe[build-essential]",
                    "recipe[redisio::default]",
                    "recipe[redisio::enable]" ]
        redisio:
          default_settings:
            requirepass: { get_attr: [redis_password, value] }
          servers:
            - name: master
              port: 6379

  redis_slave_nodes:
    type: "OS::Heat::ResourceGroup"
    depends_on: redis_master
    properties:
      count: { get_param: slave_node_count }
      resource_def:
        type: http://drop.duncancreek.net/redis_slave.yaml
        properties:
          server_flavor:    { get_param: server_flavor }
          server_hostname:  { get_param: redis_slave_hostname }
          ssh_keypair_name: { get_param: ssh_keypair_name }
          ssh_private_key:  { get_attr: [ssh_key, private_key] }
          redis_password:   { get_attr: [redis_password, value] }
          master_ip:        { get_attr: [redis_master, accessIPv4] }


outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
  redis_password:
    value: { get_attr: [redis_password, value] }
  redis_master_ip:
    value: { get_attr: [redis_master, accessIPv4]}
  redis_slave_ips:
    value: { get_attr: [redis_slave_nodes, redis_slave_ip] }
